module.exports = {
  _: {
    storage_is_encrypted: 'Mật khẩu bạn được mã hóa. Mật khẩu cần để giải mã nó',
    enter_password: 'Nhập mật khẩu',
    bad_password: 'Mật khẩu xấu, thử lại',
    never: 'không bao giờ',
    continue: 'Tiếp tục',
    ok: 'OK',
  },
  wallets: {
    select_wallet: 'Chọn ví',
    options: 'thuộc tính',
    createBitcoinWallet:
      'Hiện tại bạn chưa có ví Bitcoin. Để có thể nạp quỹ một ví Thiên Lôi Lightning , một ví Bitcoin cần phải được tạo hoặc nhập vào . Bạn có muốn tiếp tục không?',
    list: {
      app_name: 'BlueWallet',
      title: 'ví',
      header: 'Một ví có một cặp của từ khóa bí mật và một địa chỉ' + 'để bạn chia sẻ để nhận tiền mã hóa.',
      add: 'Thêm ví',
      create_a_wallet: 'Tạo ví',
      create_a_wallet1: "Nó là miễn phí và bạn có thể tạo",
      create_a_wallet2: 'nhiều ví như bạn muốn thích',
      latest_transaction: 'giao dịch mới nhất',
      empty_txs1: 'Các giao dịch của bạn sẽ hiện ra ở đây,',
      empty_txs2: 'không có gì lúc này',
      empty_txs1_lightning:
        'Ví Thiên Lôi Lightning nên dùng cho giao dịch hằng ngày của bạn.Lệ phí không công bằng và tốc độ nhanh.',
      empty_txs2_lightning: '\nĐể bắt đầu dùng chạm vào "quản lý quỹ" và nạp thêm số dư .',
      tap_here_to_buy: 'Chạm vào đây để mua Bitcoin',
    },
    reorder: {
      title: 'Sắp xếp lại ví',
    },
    add: {
      title: 'thêm ví',
      description:
        'Bạn có thể quét từ ví giấy( trong dạng WIF- Wallet Import Format), hoặc tạo ví mới. Ví Segwit tiết kiệm phí gửi được hổ trợ mặt định.',
      scan: 'Quét',
      create: 'Tạo',
      label_new_segwit: 'ví SegWit mới',
      label_new_lightning: 'Ví Thiên Lôi Lightning mới',
      wallet_name: 'tên',
      wallet_type: 'kiểu',
      or: 'hoặc',
      import_wallet: 'Nhập ví vào',
      imported: 'Đã nhập',
      coming_soon: 'Sớm có thôi',
      lightning: 'Thiên Lôi Lightning',
      bitcoin: 'Bitcoin',
    },
    details: {
      title: 'Ví',
      address: 'Địa chỉ',
      type: 'Kiểu',
      label: 'Nhãn nhận biết',
      destination: 'đích',
      description: 'mô tả',
      are_you_sure: 'Bạn chắc ne chứ?',
      yes_delete: 'Ừ, xóa mịa nó đi',
      no_cancel: 'Không, hủy bỏ ',
      delete: 'Xóa',
      save: 'Lưu',
      delete_this_wallet: 'Xóa ví này',
      export_backup: 'Xuất ra/ backup',
      buy_bitcoin: 'Mua Bitcoin',
      show_xpub: 'Xem XPUB của ví',
    },
    export: {
      title: 'xuất ví',
    },
    xpub: {
      title: 'XPUB của ví',
      copiedToClipboard: 'Đã sao chép vào clipboard.',
    },
    import: {
      title: 'nhập',
      explanation:
        "Viết các chữ gợi nhớ mnemonic, khóa riêng tư, WIF, hoặc bất kỳ thứ gì bạn nhận. BlueWallet sẽ cố géng nhiều nhứt để đoán dạng đúng và nhập vào ví bạn",
      imported: 'Đã nhập',
      error: 'Lỗi khi nhập. Làm ơn chắc rằng dữ liệu bạn cung cấp là chính xác.',
      success: 'Thành công',
      do_import: 'Nhập',
      scan_qr: 'hoặc thay vì quét mã QR?',
    },
    scanQrWif: {
      go_back: 'Đi lui lại',
      cancel: 'Hủy',
      decoding: 'Đang giải mã',
      input_password: 'Nhập mật mã',
      password_explain: 'Đây là khóa riêng tư được mã hóa theo chuẩn BIP38',
      bad_password: 'Sai mật khẩu',
      wallet_already_exists: 'Ví như vậy đã tồn tại',
      bad_wif: 'WIF không đúng',
      imported_wif: 'Đã nhập WIF ',
      with_address: ' với địa chỉ ',
      imported_segwit: 'Đã nhập địa chỉ SegWit',
      imported_legacy: 'Đã nhập địa chỉ thông thường',
      imported_watchonly: 'Nhập ví chỉ xem',
    },
  },
  transactions: {
    list: {
      tabBarLabel: 'Các giao dịch',
      title: 'transactions',
      description: 'Danh sách các giao dịch đang thực hiện hoặc gửi đi của ví của bạn',
      conf: 'conf',
    },
    details: {
      title: 'Giao dịch',
      from: 'Nhập',
      to: 'Đầu ra',
      copy: 'Chép',
      transaction_details: 'Chi tiết giao dịch',
      show_in_block_explorer: 'Xem trên Khám phá khối Block explore',
    },
  },
  send: {
    header: 'Gửi',
    details: {
      title: 'tạo gia dịch',
      amount_field_is_not_valid: 'Số lượng không hợp lệ',
      fee_field_is_not_valid: 'Phí không hợp lệ',
      address_field_is_not_valid: 'Địa chỉ không hợp lệ',
      total_exceeds_balance: 'Số tiền gửi vượt quá số dư khả dụng.',
      create_tx_error: 'Có lỗi khi tạo giao dịch. Xin vui lòng, đảm bảo địa chỉ là hợp lệ.',
      address: 'địa chỉ',
      amount_placeholder: 'số lượng gửi (tính bằng BTC)',
      fee_placeholder: 'cọng thêm phí giao dịch (tính bằng BTC)',
      note_placeholder: 'ghi chú cá nhân',
      cancel: 'Hủy',
      scan: 'Quét',
      send: 'Gửi',
      create: 'Tạo',
      remaining_balance: 'Số dư còn lại',
    },
    confirm: {
      header: 'Xác nhận',
      sendNow: 'Gửi ngay và luôn',
    },
    success: {
      done: 'Đã xong',
    },
    create: {
      details: 'Chi tiết',
      title: 'tạo giao dịch',
      error: 'Lỗi khi tạo giao dịch. Địa chỉ hoặc số lượng không hợp lệ?',
      go_back: 'Quay lui',
      this_is_hex: 'Đây là gia dịch dạng hex, đã được ký và sẵn sàng phát lên mạng lưới.',
      to: 'Tới',
      amount: 'Số lượng',
      fee: 'Phí',
      tx_size: 'kích thước TX',
      satoshi_per_byte: 'Satoshi cho một bai',
      memo: 'Ghi chú memo',
      broadcast: 'Phát đi',
      not_enough_fee: 'Không đủ phí. Hãy tăng phí',
    },
  },
  receive: {
    header: 'Nhận',
    details: {
      title: 'Chia sẻ địa chỉ với người trả tiền',
      share: 'chia sẻ',
      copiedToClipboard: 'Đã chép vào clipboard.',
      label: 'Thông tin mô tả',
      create: 'Tạo',
      setAmount: 'Nhận số tiền',
    },
  },
  buyBitcoin: {
    header: 'Mua Bitcoin',
    tap_your_address: 'Chạm vào địa chỉ của bạn để chép vào clipboard:',
    copied: 'Đã chép vào Clipboard!',
  },
  settings: {
    header: 'các cài đặt',
    plausible_deniability: 'Từ chối hợp lý ...',
    storage_not_encrypted: 'Lưu trữ: không mã hóa',
    storage_encrypted: 'Lưu trữ: được mã hóa',
    password: 'Mật khẩu',
    password_explain: 'Tạo mật khẩu mà bạn sẽ dùng để giải mã lưu trữ ',
    retype_password: 'Nhập lại mật khẩu',
    passwords_do_not_match: 'Mật khẩu không trùng nhau',
    encrypt_storage: 'Lưu trữ mã hóa',
    lightning_settings: 'Cài đặt Thiên Lôi Lightning',
    lightning_settings_explain:
      'Để nối tới nốt mạng LND của bạn làm ơn cài đặt phần mềm LndHub' +
      " và đặt URL của nó ở đây. Để trống nếu muốn dùng cụm nút mạng LNDHub của BlueWallet (lndhub.io). Các ví sẽ được  tạo sau khi lưu các thay đổi và nối tới các cụm nút mạng LNDHub đã cài .",
    electrum_settings: 'Cài đặt Electrum',
    electrum_settings_explain: 'Để trong để dùng cài đặt mặc định',
    save: 'Lưu',
    about: 'Về chúng tui',
    language: 'Tiếng nói',
    currency: 'Tiền tốt',
    advanced_options: 'Các cài đặt nâng cao',
    enable_advanced_mode: 'Kích hoạt chế độ nâng cao',
  },
  plausibledeniability: {
    title: 'Từ chối hợp lý',
    help:
      'Trong một số trường hợp nhất định, bạn có thể bị buộc phải tiết lộ ' +
      'mật khẩu. Để giữ tiền bạn an toàn, BlueWallet có thể tạo một ' +
      'lưu trữ mã hóa khác, với mật khẩu khác. Dưới áp lực nào đó, ' +
      'bạn có thể nói mật khẩu này cho bên thứ 3. Nếu vào trong ' +
      "BlueWallet, nó sẽ mở khóa một lưu trữ giả. Điều này dường như " +
      'sẽ hợp lý cho bên thứ 3, nhưng sẽ giữ phần lưu trữ chính của bạn  ' +
      'chứa tiền bạn an toàn.',
    help2: 'Lưu trữ mới sẽ đầy đủ chức năng, và bạn có thể trữ một số ' + 'nhỏ tiền ở đó để nó trông có vẻ đáng tin cậy.',
    create_fake_storage: 'Tạo lưu trữ mã hóa giả',
    go_back: 'Quay lui lại',
    create_password: 'Tạo mật khẩu',
    create_password_explanation: 'Mật khẩu cho lưu trữ giả NÊN không trùng với kho trữ chính của bạn',
    password_should_not_match: 'Mật khẩu cho lưu trữ giả NÊN không trùng với kho trữ chính của bạn',
    retype_password: 'Nhập lại mật khẩu',
    passwords_do_not_match: 'Mật khẩu không khớp, thử lại nhé ',
    success: 'Thành công',
  },
  lnd: {
    title: 'quản lý quỹ',
    choose_source_wallet: 'Chọn ví nguồn',
    refill_lnd_balance: 'Nạp tiền cho ví Thiên Lôi  Lightning',
    refill: 'Nạp',
    withdraw: 'Rút',
    expired: 'Hết hạn',
    placeholder: 'Hóa đơn',
    sameWalletAsInvoiceError: 'Bạn không thể chi trả cho hóa đơn được tạo bởi cùng một ví đã tạo ra nó.',
  },
  pleasebackup: {
    title: 'Ví của bạn đã được tạo...',
    text:
      "Làm ơn bỏ chút thời gian Bitcoin để viết lại các chữ gợi nhớ mnemonic vào miếng giấy với bút không phay màu theo thời gian. Việc sao lưu này được dùng để khôi phục lại ví ở thiết bị khác. Bạn có thể dùng phần mềm ví Electrum trên máy tính (https://electrum.org/) để khôi phục ví giống y chang ví này.",
    ok: 'OK, TUI ĐÃ VIẾT NÓ RỒI!',
  },
  lndViewInvoice: {
    wasnt_paid_and_expired: 'Hóa đơn này chưa được chi trả và đã hết hạn',
    has_been_paid: 'Hóa đơn này đã được chi trả',
    please_pay: 'Làm ơn chi trả',
    sats: 'sats',
    for: 'Cho:',
    additional_info: 'Thông tin thêm',
    open_direct_channel: 'Mở một kênh trực tiếp tới nút mạng :',
  },
};
